sudo: false
language: node_js
cache:
  bundler: true
  directories:
    - node_modules
notifications:
  flowdock: e7454f5285e7b9ab67009802d5560490
node_js:
- '0.10'
deploy:
  provider: npm
  skip_cleanup: true
  clean_up: false
  email: serveradmin@octoblu.com
  api_key:
    secure: kYmDR32n2b7CpglPXKdgk1LcD88mJ1w+GvOm3kcyA5W3MbqmqiIj9GV42TdjOrTH5PKlHW0RKPKa/c8T0Qcq9cu2FJvTsA63H9b8S6QSpxd6b2q+xhrECp3N6njXVVe7FFt2VJt6We+bpzDja5v7Liz7QSTj+nDDTMSSZPEcc5Q=
  on:
    tags: true
    all_branches: true
