sudo: false
language: node_js
cache:
  bundler: true
  directories:
    - node_modules
notifications:
  flowdock: e7454f5285e7b9ab67009802d5560490
node_js:
- '0.10'
deploy:
  provider: npm
  skip_cleanup: true
  clean_up: false
  email: serveradmin@octoblu.com
  api_key:
    secure: LFhLCSYGCe4vI7vRCQXMySLBqx95mYSPJyHBP0m0+uzwRPRW1uq+ifzmhDxpfrjDGyWdC7sAxKPhczChg9JFweItJx/GkKEwc8yIxmpL1TjjixuRc1IRkmnWEgcD73P6TCBCbgOXH/VWB6Sg8H2fhTO6lofgdnQv/euU3Z9Wwf0=
  on:
    tags: true
    all_branches: true
