sudo: false
language: node_js
node_js:
- '5'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
deploy:
  provider: npm
  skip_cleanup: true
  clean_up: false
  email: serveradmin@octoblu.com
  api_key:
    secure: kp5mq1LrM0d+cQyF1BPZSEuyn4e0siXNXJ/McJajXr8+KggrwB0QaHFpAdcJsLgjOkdD9BtR2leQBB+kZ2iF05bo0EXBkBFtnBnWzIwKuYQQ7yt1jTlnE1Flxd7M8K0h1Pow4NIXst/tQdygPD6IMGYF9R/j23mj+FrkzX7wVik=
  on:
    tags: true
    all_branches: true
