sudo: false
language: node_js
node_js:
- '5'
deploy:
  provider: npm
  skip_cleanup: true
  clean_up: false
  email: serveradmin@octoblu.com
  api_key:
    secure: Tv9HhnIjNklDyrTvzUTlKv64cc+I8giA6gcnzpE1mUEKgxJsMIcxIaoTDRrX3a7EpysLRZAtT6ub8qVKKOVUgUfdnVNIZ9Q3jAdSKqH8rr2AJTpAKtEXrQapMNWfPdpDYn/Ys3fiWp9stEAWka1QP8DL7JBZCaOmsNKlm3OM+YI=
  on:
    tags: true
    all_branches: true
